services:
  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_DB: computers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "sleep 3 && migrate -path=/migrations -database=postgres://postgres:mypassword@db:5432/computers?sslmode=disable up"
      ]

volumes:
  pgdata:
